# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

strategy:
  matrix:
    #PLATFORM: [ "x86", "x64" ]
    buildConfiguration: 'Debug,Release'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


#variables:
#  buildConfiguration: 'Debug,Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
